### ISSUE TITLE
Demo accepts file URIs

### ISSUE THREAD

**Issue by me4** [chrisiaut/http2pic#13]
It looks like wkhtmltoimage and phantomjs are called in such a way that file URLs are not blocked. This gives access to files on the server by passing a URL like file:///etc/X11/rgb.txt .

I can see the file contents in the output at https://http2pic.haschek.at/api.php?url=file%3A%2F%2F%2Fetc%2FX11%2Frgb.txt

**Comment by geek-at** [comment]
oh neat, thanks for the info
