### ISSUE TITLE
Problem with some URLs

### ISSUE THREAD

**Issue by yvangodard** [chrisiaut/http2pic#14]
I have implemented it on some projects, but have a bug on some URLs. 
Could you just tell me if the problem is related to your API or to my url. 
For example : https://http2pic.haschek.at/api.php?url=https://www.reseauenscene.fr/email.php?ID=1a9ae4 wont work but https://http2pic.haschek.at/api.php?url=https://www.reseauenscene.fr works well. Any idea ? Thanks a lot for ur huge tool !

**Comment by geek-at** [comment]
Pretty sure it has something to do with URL encoding because your URL is using the reserved character "?". I tried with an encoded URL but it doesn't work, I'll look into the code maybe I can fix it

**Comment by yvangodard** [comment]
@geek-at  Any news ? 
Your tool is really helpful for us, so if we need to pay to solve this issue it won't be a problem ...
I understand that maintaining some opensource lib and tools need some time ... but it would be great to solve this issue.
Feel free to contact us !

**Comment by geek-at** [comment]
Oh sorry totally doged my radar. Should be fixed now.

Wow though I've written the code in 2015 and I'd do many things differently. If you have a budget I'd be happy to bring this code base to the year 2022 and probably dockerize it so the setup will be a breeze.

If you do have a budget and want it maintained you can reach me at christian@haschek.at
