### ISSUE TITLE
option to set longer load time

### ISSUE THREAD

**Issue by davidvasandani** [chrisiaut/http2pic#3]
Some websites don't fully load by the time the picture is taken.

Example: https://http2pic.haschek.at/api.php?url=warbyparker.com

Is it possible to add an option to extend the load time?

**Comment by lekoaf** [comment]
You can set a timeout that ranges from 1-30. I'm guessing that's seconds. Just add `&timeout=30` to your url.

**Comment by geek-at** [comment]
Exactly. You can set the timeout higher with a simple change in the api.php file. I didn't make it higher than 30 seconds for the public api
